services:
  atm:
    image: ghcr.io/zekrotja/sf5-dockerized:latest
    restart: unless-stopped
    environment:
      XMS: 4G
      XMX: 8G
      MAX_AGE_BACKUP_FILES: 30d
      PRE_START_BACKUP: "false"
      POST_START_BACKUP: "false"
    ports:
      - "25823:25565"
    volumes:
      - "./sf5/world:/var/mcserver/world"
      - "./sf5/config:/var/mcserver/config"
      - "./sf5/whitelist.json:/var/mcserver/whitelist.json"
      - "./sf5/ops.json:/var/mcserver/ops.json"
      - "./sf5/server.properties:/var/mcserver/server.properties"
