name: Docker Autobuild
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  docker:
    name: Docker Autobuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          no-cache: true
          tags: |-
            ghcr.io/${{ env.REPO }}:latest
